### ISSUE TITLE
Found argument 'polkadot' which wasn't expected, or isn't valid in this context

### ISSUE THREAD

**Issue by bneiluj** [paritytech/polkadot#1]
**Bug:** 

The command line `docker run --rm -it chevdor/polkadot:latest polkadot --name "PolkaDocker"` crashes before executing. 
```
docker run --rm -it chevdor/polkadot:latest polkadot --name "PolkaDocker"
error: Found argument 'polkadot' which wasn't expected, or isn't valid in this context

USAGE:
    parity [SUBCOMMAND]
```
**Expected:** 

Have the docker image running. 

**Workaround:** 

If `polkadot` argument is removed then it executes correctly. 
`docker run --rm -it chevdor/polkadot:latest --name "PolkaDocker"`

**Env:** 
`Parity version Parity-Ethereum/v2.1.0-nightly-4eab867-20180810/x86_64-linux-gnu/rustc1.28.0`

**Comment by chevdor** [comment]
Thank you @bneiluj for taking the time to fill up this issue.

The described issue only affects the `latest` image currently in docker hub.
Workaround: exclude `polkadot` as mentioned by @bneiluj above.

This requires no change in the code. I will rebuild and push/overwrite latest.

**Comment by chevdor** [comment]
This issue is no longer valid.
The version of the image in docker hub is now 0.2.14 and the issue described above is gone.

Using `docker run --rm -it chevdor/polkadot:latest polkadot --name "PolkaDocker"` now works as we can see below:
![image](https://user-images.githubusercontent.com/738724/45300749-7fea5280-b50f-11e8-9a77-56775e8aafcd.png)

Thanks again for taking the time to report the issue @bneiluj
