### ISSUE TITLE
Pin Rust Toolchain versions upon releases

### ISSUE THREAD

**Issue by wpank** [paritytech/polkadot#1163]
Right now we have floating toolchain versions, which can lead to build errors like paritytech/substrate#6167 when using certain nightly versions. Upon releases for Polkadot / Substrate we should pin the toolchain versions for build reproduceability.

**Comment by bkchr** [comment]
This is a Polkadot "issue" ;)

**Comment by bkchr** [comment]
We should also add instructions on how to install the specific rust versions and how to use them to compile the release. This could also be done as a link to some generic instruction where the user just needs to set the correct rustc versions.

**Comment by bkchr** [comment]
CC @JoshOrndorff maybe you want to create a guide for installing any rustc version stable & nightly and how to build with this version.

**Comment by xlc** [comment]
A toolchain file should solve most of the problem?

**Comment by bkchr** [comment]
This only works for people who use rustup and it adds another file that needs to be manually tracked. Our CI is testing each new nightly and updates the CI images only when Substrate can be build. The release script just needs to print the rustc versions that can be found in the image, which makes this 100% automated the the favored solution.

**Comment by JoshOrndorff** [comment]
I'm happy to create a guide if it is helpful, but I would have to teach myself how to do it without rustup. All the devhub products and tutorials assume the user is using rustup. Is there a compelling reason not to require rustup? I think https://doc.rust-lang.org/nightly/edition-guide/rust-2018/rustup-for-managing-rust-versions.html is already a pretty nice guide.

**Comment by wpank** [comment]
@JoshOrndorff 

https://wiki.polkadot.network/docs/en/mirror-maintain-guides-how-to-validate-kusama#building-and-installing-the-polkadot-binary
I added a note here on it, but I'm sure there's better solutions.

**Comment by bkchr** [comment]
> @JoshOrndorff
> 
> https://wiki.polkadot.network/docs/en/mirror-maintain-guides-how-to-validate-kusama#building-and-installing-the-polkadot-binary
> I added a note here on it, but I'm sure there's better solutions.

This should be generalized, aka the user needs to supply the correct version that will be part of the release message.

**Comment by s3krit** [comment]
So to be clear and to sum up the issue:

- We *don't* want to provide a `rust-toolchain` file
- We simply want to extract the necessary `rust-nightly` version from the last successful nightly CI build, and provide that in the release-notes as an instruction that the User can use in order to succesfully build Polkadot.

Is this correct? Also, it would obviously be possible to automate the creation of the `rust-toolchain` file but for that to be effective, we'd have to have CI making commits against master (or else have it create a PR and have someone manually merge every day...) and I don't think we're in that place yet.

**Comment by bkchr** [comment]
> We simply want to extract the necessary rust-nightly version from the last successful nightly CI build, and provide that in the release-notes as an instruction that the User can use in order to succesfully build Polkadot.

We should also extract the stable compiler version.

**Comment by danforbes** [comment]
Has the Substrate build been updated to include changes as in https://github.com/paritytech/polkadot/pull/1191? I see that this Issue was moved from the Substrate repo and it seems like this would be something that would be nice for Substrate to have. I'm still not entirely clear why it's not desirable to use CI to generate a toolchain file for our releases...

**Comment by bkchr** [comment]
The point was that this file is not tracked in git and needs a pr each time to update it.

**Comment by danforbes** [comment]
That seems like the sort of thing that could be easily automated with CI. Also, do you know if complementary changes to #1191 have been made in the Substrate repo?

**Comment by bkchr** [comment]
There was no complementary changes AFAIK. But not sure it is needed there, we don't release any binary for Substrate.

**Comment by danforbes** [comment]
I consider the Substrate node template and the other resources in the `bin` directory to be binaries that are released as part of an official Substrate release.
