### ISSUE TITLE
Provide better errors messages on transaction failure

### ISSUE THREAD

**Issue by Demi-Marie** [paritytech/polkadot#1311]
https://github.com/polkadot-js/apps/issues/3033 was closed as “not a bug”, but there definitely needs to be some conversion from machine-readable error codes to localizable, human-readable error messages.

**Comment by thiolliere** [comment]
if the error type for failing filters want to be improved, one can introduce a new system error and change this line https://github.com/paritytech/substrate/blob/73318f426dc392352060c59e4b896eaae2af58ac/frame/support/src/dispatch.rs#L1925

But actually I feel like the error indicate correctly the reason for the fail, the call can't be dispatched because the origin is not valid to call this. i.e. the origin is bad. in polkadot making a transfer with a signed accont is (at the moment) not allowed.

**Comment by DemiMarie-parity** [comment]
@thiolliere That is technically true, but the name `BadOrigin` isn’t particularly helpful to users.  More specifically, `BadOrigin` made me think that the account I was sending the transaction from was invalid, or that the transaction was somehow ill-formed.  I would prefer an error like “The origin account is not authorized to make this transaction,” indicating that the transaction may have been correct, but the transaction is being intentionally rejected.
