### ISSUE TITLE
how to deal with Provided Host header is not whitelisted.

### ISSUE THREAD

**Issue by LeoNg8120** [paritytech/polkadot#1410]
request:http://192.168.3.25:9933

respon:Provided Host header is not whitelisted.

but i can't find config file in the docker.
How should I add ip to whitelisted.

this is my run args:

sudo docker run \
             -m 5G \
             --name polka \
             --oom-kill-disable \
             --cpus="1.5" \
             -d \
             -p 30333:30333 \
             -p 9933:9933 \
             -p 9944:9944 \
             -v `pwd`/data:/data \
             chevdor/polkadot \
             polkadot --rpc-external --ws-external --chain westend

**Comment by tomusdrw** [comment]
Since by default only the interface the node is listening on is whitelisted as `Host` and you are running within a docker container, you need to set `--rpc-cors=all` to disable that. Unfortunately it has an extra consequence of turning of `Origin` header verification, so it's possible for any page running in your browser to make requests to your node.

A more secure setup would include an `nginx` reverse proxy to have full control over these kind of settings.
