### ISSUE TITLE
Introduce a Runtime API for checking results against TransientValidationData

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#1594]
This will allow logic to be shared on the node-side and runtime code for checking candidate commitments.

After #1539

**Comment by pepyakin** [comment]
My proposal here is to do the following.

First, from the runtime side we introduce a new Runtime API that allows checking the candidate commitments against the current state. This code is the same that is used as part of the inclusion checks. The changes for this part are already available as part of #1679 , specifically [the diff](https://github.com/paritytech/polkadot/pull/1679/files/43350ba3e9c089b93e3c95cc63d8197d3dc3d02f..93bff6650628609a60596e3ee5ff92823e49d23c).

Second, we should restructure the candidate-validation subsystem. My proposal is this. Based on the two groups of use-cases, i.e. the secondary checkers vs. non-secondary checkers (i.e. backing, optionally collating), we would have two messages:

1. `FullValidation`
1. `PartialValidation`

(names are subject for change)

the `FullValidation` message would be handled by the querying the `PersistentValidationData` from the runtime api subsystem (i.e. implies the state is available), then using this `PersistentValidationData` we would form inputs, execute PVF and then unconditionally (although that's a subject for discussion) ask the aforementioned API to validate the candidate commitments obtained from the PVF execution.

The `PartialValidation` message would carry `PersistentValidationData`, so that it won't imply the availability of state but also won't check the validitity of commitments.
