### ISSUE TITLE
Subsystems should be resilient to errors

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#1602]
Unfortunately, we have a lot of cases where races between message delivery and job cleanup can cause such issues.

The subsystems should generally be more robust, and should simply log the error and move on if communication fails.

**Comment by ordian** [comment]
Once this is resolved, we should revert https://github.com/paritytech/polkadot/pull/1884.

**Comment by ordian** [comment]
Let's repurpose this issue as a tracking issue for making all error non-fatal: https://github.com/paritytech/polkadot/pull/1888#issuecomment-719642838.

**Comment by ordian** [comment]
Now that we make all subsystems resilient to errors, the only source of errors that is left is `ctx.send_message`. This can fail if Overseer is down (it seems the only reason, please correct me if I'm wrong). But Overseer can be down if one of the subsystems is down. We have a chicken and egg problem here :)

So I propose to change `send_message` not to return an error and use `expect` instead.
Otherwise error handling is quite cumbersome as seen in https://github.com/paritytech/polkadot/pull/1908/commits/7f32419243eff1e65ec5f59ce388bc54e7a4153a.

**Comment by bkchr** [comment]
If you can not send to the overseer anymore, why not bring down the subsystem?

We should *not* use `expect`. If we a certain that we don't need the error to bring the subsystem down, we could just ignore any errors when sending a message to the overseer.

**Comment by ordian** [comment]
> If you can not send to the overseer anymore, why not bring down the subsystem?

Maybe using `expect` is not the best idea, but why would be a subsystem not able to sent to the overseer? Doesn't it imply overseer is down and hence we will panic soon?

**Comment by bkchr** [comment]
Sending only fails when the receiver is down. Why should we panic when the overseer is down? Maybe the node is just shutting down legally or something else failed. But if there is no reason for panicking, we should not panic. And not being able to send is clearly not a case where we should panic ;)

**Comment by ordian** [comment]
Yeah, then we could ignore or log the error and change the return type of `send_msg` to `()` instead of `SubsystemResult<()>`.
