### ISSUE TITLE
lost my coin

### ISSUE THREAD

**Issue by wo4zhuzi** [paritytech/polkadot#1653]
lost my coin,
address "12AMKPVsdrGJeiwS1Rc9iNtuNF7K7vV4rKppYRmvzvxHaCKP"
Query results  "https://polkadot.subscan.io/account/12AMKPVsdrGJeiwS1Rc9iNtuNF7K7vV4rKppYRmvzvxHaCKP?tab=transfer"

address_balance !=  receive_balance - send_balance - fee

@apopiak @shawntabrizi

**Comment by NikVolf** [comment]
https://polkadot.subscan.io/extrinsic/0xa5cd4ddc5617e9f817890ef71630d92c7db76a18254bb199670c615a9445ab36

If you look for a transaction that transferred 1 dot from `12AMKPVsdrGJeiwS1Rc9iNtuNF7K7vV4rKppYRmvzvxHaCKP`, you see `system(KilledAccount)` event there

This is because after this transaction, balance of  `12AMKPVsdrGJeiwS1Rc9iNtuNF7K7vV4rKppYRmvzvxHaCKP` is pushed below existential deposit which I believe is 1 DOT.
