### ISSUE TITLE
one extrinsic in two blocks

### ISSUE THREAD

**Issue by zhp1254** [paritytech/polkadot#1672]
https://polkascan.io/polkadot/transaction/0xaae5400ed9fe5bed10f2085c5e5773e1fc7f1ebff24793bf9540752295b17c1b

this extrinsic exists in block 1404023 and block  1405128，And it cost two fees

and the from address nonce is reset

**Comment by NikVolf** [comment]
If you look for a transaction https://polkascan.io/polkadot/transaction/0x09c155ab7d2c7c9ea8e586bdb98e621245be72d79363ccc8dfff77d23c60cf89, it has `KilledAccount` event in there

this is because balance of `12QKFAZDFCjuCyX4j8n4LqZgMJggN7Lu6UpDHVUNfVrEY5Gf` dropped below 1 dot in this transaction (so-called "existential deposit")

After this kill, nonce is reset to 0, this is why some transaction in future might have the same hash

**Comment by zhp1254** [comment]
> If you look for a transaction https://polkascan.io/polkadot/transaction/0x09c155ab7d2c7c9ea8e586bdb98e621245be72d79363ccc8dfff77d23c60cf89, it has `KilledAccount` event in there
> 
> this is because balance of `12QKFAZDFCjuCyX4j8n4LqZgMJggN7Lu6UpDHVUNfVrEY5Gf` dropped below 1 dot in this transaction (so-called "existential deposit")
> 
> After this kill, nonce is reset to 0, this is why some transaction in future might have the same hash


We only broadcast the transaction `0xaae5400ed9fe5bed10f2085c5e5773e1fc7f1ebff24793bf9540752295b17c1b` once
