### ISSUE TITLE
How will parachain throughput be throttled by the relay chain

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/polkadot#1879]
This issue is primarily a request for guidance regarding how, if at all, the relay chain will throttle parachain throughput. If this information already exists in code, documentation, or research, pointing to it is sufficient. If it doesn't yet exist, this is to start the conversation.

## Context

The Moonbeam team is beginning to consider hardware specs for collators. In sovereign blockchains, more throughput can typically be gained by requiring more substantial hardware on the validators. We're wondering if there s an upper limit on that imposed by the relay chain.

## Some thoughts

Relay chain validators will validate parachain blocks in two scenarios. First for the candidate blocks from the parachain they are assigned to, and second in secondary checks. This validation happens in wasm, and presumably has to fit within the relay chain's block time for validators runnning hardware determined by the relay chain.

**Comment by burdges** [comment]
We'll cap size of course.  We also time blocks so that if a block takes too long then that block is invalid.  

We discuss validation timeouts in https://github.com/paritytech/polkadot/pull/1656/files but two relevant take aways:  

We're less worried about validators being slow than about them being unpredictable, which limits wasmtime exploiting the latest fancy AVX-512 instructions, etc. 

We want slow blocks to always be rejected by backing validators, so any backing validator abandons blocks way faster than approval checkers do, like 6 times earlier, although 18 times earlier sounds plausible too.  You'll only have a few backing checkers assigned, so if collators could miss slots if they push the timeouts too much.

**Comment by rphmeier** [comment]
outdated
