### ISSUE TITLE
guide: Inclusion Module: process_bitfields clarification

### ISSUE THREAD

**Issue by coriolinus** [paritytech/polkadot#1915]
https://github.com/paritytech/polkadot/blob/master/roadmap/implementers-guide/src/runtime/inclusion.md

> * `process_bitfields(Bitfields, core_lookup: Fn(CoreIndex) -> Option<ParaId>)`:
>   1. check that the number of bitfields and bits in each bitfield is correct.
>   1. check that there are no duplicates
>   1. check all validator signatures.
>   1. apply each bit of bitfield to the corresponding pending candidate. looking up parathread cores using the `core_lookup`. Disregard bitfields that have a `1` bit for any free cores.
>   1. For each applied bit of each availability-bitfield, set the bit for the validator in the `CandidatePendingAvailability`'s `availability_votes` bitfield. Track all candidates that now have >2/3 of bits set in their `availability_votes`. These candidates are now available and can be enacted.
>   1. For all now-available candidates, invoke the `enact_candidate` routine with the candidate and relay-parent number.
>   1. Return a list of freed cores consisting of the cores where candidates have become available.

Step 1: What constitutes the correct number of bitfields should be explicit.
Step 1: What constitutes the correct number of bits in a bitfield should be explicit.
Step 7: This step does not agree with the function signature

**Comment by burdges** [comment]
We'll check the signatures when we put these on-chain.

`AvailabilityBitfield::submitted_at` might make more sense if called `submitted_for` or `relay_parent` because it's the signer's opinion that matters not the relay chain block "at" which it gets put on chain.  We've some map `fn previously_freed_cores(current_block,submitted_for) -> BitVec` so then 
```
impl AvailabilityBitfield {
    fn in_context(&self, current_block) -> BitVec {
        self.bitfield & ! previously_freed_cores(current_block, self.submitted_for)
    }
}
```
We can then run a counter across these on the `bitfields` storage item to return the list of votes that do inclusion and free cores in the current block.

**Comment by rphmeier** [comment]
@burdges At the moment Polkadot only accepts bitfields for the most recent relay parent. Accepting bitfields from `k` blocks back is "future work" : )

**Comment by burdges** [comment]
I suppose most recent suffices if the gossip were synchronous/fast enough.  We'll likely encounter older availability votes, so accepting older might help with adding more validators, etc.  

Anyways, It's fine if this gets punted to future work.  We'll vastly improve our triage/prioritization capabilities once anything gets running.  :)

**Comment by rphmeier** [comment]
> Actually most recent suffices if the gossip were synchronous/fast enough. We'll likely encounter older availability votes, so accepting older might help with adding more validators, etc.

Yeah, this was my thought process as well. The gossip speeds we've observed with GRANDPA make me think that we'll be fine but might want to allow bitfields that are up to 2 blocks old at some point. If we identify availability as a bottleneck this is an optimization that would be important.

**Comment by burdges** [comment]
If I understand, you still vote on older backings here, but if some node has trouble being up date with the relay chain, then they've trouble including their availability votes.  A priori, these slow nodes have other issues, but they could exist because we're making them validate many chains.  It's probably that most recent limits our ability to degrade gracefully as we ask for more work.

**Comment by rphmeier** [comment]
outdated questions
