### ISSUE TITLE
Optimize Availability Distribution: direct distribution

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#1979]
Currently gossip, which is terribly inefficient.

We need some guide changes first, but then might repurpose this issue to handle implementation.

@infinity0 has a document describing how the topology might be best constructed, so the guide changes are really just about how exactly we plan to implement those with our real network APIs.

**Comment by burdges** [comment]
As a topology for availability, I'd expect direct TCP connections between everyone should work fine through 1000 validators.  At some point, it'll exhaust RAM but switching to quinn (QUIC) and then paying the quinn devs to optimize their code helps. 

Afaik all validators topology discussion have came out inconclusive for availability distribution and reconstruction.. or worse ignored reconstruction.  We'll eventually reach other scaling bottlenecks anyways, like availability bitfields are quadratic, grandpa degrades by batch finalizing, etc.  

We should therefore defer fancy topologies until we actually witness real bottlenecks.  We'll face this system parachain problem for hierarchical chains of course, but maybe solving that solves all our topology problems too.

**Comment by rphmeier** [comment]
That's fair. So you suggest we should in fact just directly distribute pieces to validators with TCP? I can get on board with that.

**Comment by burdges** [comment]
Yes.  It's clearly better to distribute them directly by whatever means.  I'd wager the code bloat and maintenance work for both TCP and QUIC direct distribution amounts to less than for maintaining both QUIC direct and inefficient gossip distribution.

**Comment by rphmeier** [comment]
We can also use direct distribution similar to the availability recovery subsystem: #2011

**Comment by eskimor** [comment]
From discussion, starting point for an approach:

Alter the network bridge:

- Maintain a mapping of all validators from the current and past session. potentially upcoming as well
- Attempt to maintain connections with each of them
- Introduce a notion of ‘dormant’ peers. We’ll have some small amount of peers who are ‘active’, and those are the ones we’ll actually gossip with. Dormant by default, and then a handshake of some kind to activate. We could also do this lower-down, at the level of the gossip-protocols, but the principle is that you have to tell a node that you consider it active before you accept any gossip data (more broadly, ‘non validator-specific’ data from it).
- Introduce a request for subsystems to ask for PeerIds of validators, either by ValidatorId or AuthorityDiscoveryId.

- Alter higher level protocols in subsystems):

- Instead of asking for connections to validators, we can assume that the bridge is actively trying to connect to all validators and just ask for PeerIds.

Those direct 'dormant' connections are also very useful for availability recovery at least.

**Comment by eskimor** [comment]
Current approach, have validators directly request their pieces based on occupied cores from backing group. See [here](https://github.com/paritytech/polkadot/pull/2423).

**Comment by eskimor** [comment]
Superceded by #2306
