### ISSUE TITLE
Relay chain blocks can swell due to oversized candidates, potentially stalling the chain

### ISSUE THREAD

**Issue by pepyakin** [paritytech/polkadot#2157]
Currently, a relay chain block author would put all backed candidates that is available into the block. That may be problematic since a backed candidate can be very heavy in case it carries a PVF code upgrade. Depending on configuration it may happen that two candidates upgrading code would make a block to exceed the max block size. Because block proposer is dumb and will try to shove the candidates into the block greedely, I see such an event could lead to the relay chain stalling.

I think that possibility of this happening accidentally is really low. However, it's quite possible that parachains could coordinate in order to exploit this issue. 

In order to mitigate the issue we could teach the block proposer to keep an eye on the size of the relay-chain somehow. In this direction, should more than one parachain update code, only one can win, other candidates are discarded (or wait, until next block, in case we have contextual execution). 

Another direction is to introduce scheduling, so that candidates with upgrades can be included only at specific blocks, but that's both inconvenient and wouldn't work great with contextual execution.

**Comment by burdges** [comment]
Just another option:

We need PVFs be available to all validators.  We could eventually do this via the availability system.  It'd go:  First some parachain block contains only its new upcoming PVF, but subsequent parachain blocks continue using the old PVF.  After this parachain block becomes available (resp. finalized maybe) then another parachain block could references this blocks availability (resp. finality proof from BEEFY) which then switches the PVF.  At this point, any validator can reconstruct the code if assigned, which requires caching the code.

This requires the PVF only block remain available indefinitely until replaced, as opposed to 24 hours.  This requires validators hand off pieces, or incoming validators reconstruct, which sounds like a mess and definitely not part of any MVP.  

All this complexity would be warranted only if validator and/or PVFs have high enough churn, but we hope the opposite.  In the short term either of your suggestions make much more sense, and hopefully in the long term too.  We might however make the availability system friendly enough that the barriers become rather lower one day.

**Comment by rphmeier** [comment]
The only way that `CommittedCandidateReceipt`s actually get heavy is to include a code upgrade. Since these are rare and limited by the relay chain, we can tweak the provisioner and the inclusion inherent to only select and include up to one candidate that contains a code upgrade per block. In the rare cases that there are two paras trying to upgrade their code at the same time, one of them will just have to wait 6 seconds.

**Comment by coriolinus** [comment]
So, if we have a struct like 

```rust
struct AnnotatedCandidateReceipt {
  receipt: CandidateReceipt,
  contains_code_upgrade: bool,
}
```

with appropriate conversion methods (from `CommittedCandidateReceipt` and into `CandidateReceipt`, then it's simple to have the Backing subsystem send `AnnotedCandidateReceipt`s as part of the `ProvisionableData`, and have the provisioner select at most one which contains a code upgrade. It's not clear to me why we'd need to edit the inclusion inherent at all.

(The reason to create `AnnotatedCandidateReceipt` at all instead of just sending `CommittedCandidateReceipt`s is that the provisioner keeps a list of them in memory, so storing the existence of a code upgrade as a bool instead of the actual upgrade saves quite a bit of memory.)

**Comment by rphmeier** [comment]
@coriolinus Couldn't it simply be done by tracking a `bool` within `fn select_candidates`?

**Comment by coriolinus** [comment]
Yes, that's right, but given just a `CandidateReceipt`, we don't know what the value of that `bool` should be. That's why we introduce `AnnotatedCandidateReceipt`.

**Comment by rphmeier** [comment]
OK, that seems reasonable
