### ISSUE TITLE
client crashes - tokio-runtime-worker panicked, previously known block disappeared

### ISSUE THREAD

**Issue by VasiliyS** [paritytech/polkadot#233]
polkadot 0.4.3 crashes and can't sync anymore.

First the following crash happened:
[tokio-runtime-worker 1.txt](https://github.com/paritytech/polkadot/files/3120912/tokio-runtime-worker.1.txt)

Node re-started and was syncing for a while, then the next one happed:

[tokio-runtime-worker 2.txt](https://github.com/paritytech/polkadot/files/3120913/tokio-runtime-worker.2.txt)
Every time I restart the node crashes with the same error.

**Comment by lsaether** [comment]
Ran into this too after upgrading from 0.4.3 to 0.4.4.
```
-stack trace snipped-

Thread 'tokio-runtime-worker-2' panicked at 'Previously known block 0xb4871f08c4c9326e47a967f72623790fff8b3711135554329b681241ddbd8c31 has disappeared from chain', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/finality-grandpa-0.6.0/src/voter.rs:397
```


Tried to do `polkadot revert` and got:
```
2019-05-10 08:59:44 There aren't any non-finalized blocks to revert.
```

Appears that the only solution is to `polkadot purge-chain` and re-sync from scratch. Is this right? Would be nice to at least get a little more info if this is a known bug since also #228 reports it.

Possibly what happened was I re-built the native code without re-building the runtime code, would that cause this issue?

**Comment by gavofyork** [comment]
Closing as stale.
