### ISSUE TITLE
Statement distribution likely does not connect properly to the validator peer set.

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot#2400]
See discussion [here](https://github.com/paritytech/polkadot/pull/2372#issuecomment-775238276)

**Comment by eskimor** [comment]
Ok, it will take me a bit longer to look into this. If anyone wants to pick this up sooner - be my guest :-) It is not super critical as connections seem to work since #2372 .

**Comment by rphmeier** [comment]
Statement distribution doesn't need to connect to the validator set as it's meant to be a gossip protocol where all validators see all statements. The statements themselves are light in the case of code upgrades. although we should optimize this later on.

The reason all validators need to see all statements is because the block author needs to include backed candidates from _all_ parachains, not just its own group. And in BABE or SASSAFRAS (future), the block author isn't known to other nodes.

**Comment by rphmeier** [comment]
What this "bughunting" issue is really about is ensuring that statements are propagating correctly among all nodes.

**Comment by eskimor** [comment]
In particular it should be checked that connections on the validation peer set are actually opened before messages are being sent to a particular peer.

**Comment by eskimor** [comment]
Closing, as obsoleted by #2536 .
