### ISSUE TITLE
Unable to spend DOT from account that has existential deposit

### ISSUE THREAD

**Issue by APshenkin** [paritytech/polkadot#2485]
I have account that has 1 DOT exactly. I try to create transfer (not transfer keep alive) transaction to move some part of dot to other account (I tried different amounts - 0.9, 0.5, 0.1). But each time when I try to broadcast transaction I recieve this error:

```
{"jsonrpc":"2.0","error":{"code":1010,"message":"Invalid Transaction","data":"Inability to pay some fees (e.g. account balance too low)"},"id":1}
```

Simple transfer usually requires ~ 0.0155 DOT for fees so there is enough balance for complete transfer. 
This case is reproduced with 1 DOT balance. When I send 2 DOT to other account and create transaction to withdraw the whole balance it works like a charm.

**Comment by shawntabrizi** [comment]
@APshenkin The logic of the chain right now is that fees cannot kill an account.

Fees are taken out of the account before we even know what kind of transaction is happening or what amount of balance you may transfer.

As such, when you have exactly 1 DOT, you cannot make any transactions from your account which would take any fees. Instead, you must add enough so that after the fee is taken, you still have existential deposit, and then you can do the transfer.

Potentially we may be able to optimize this specific scenario, but it does not feel to me a priority.

**Comment by gituser** [comment]
Super stupid decision to not allow to transfer if account's balance is exactly **1 DOT**.

If user sends exactly 1 DOT to the deposit address you won't be able to transfer it until you top it up. Even small amount of 0.01 will help you to transfer 1.01, but not 1 DOT minus fees.
