### ISSUE TITLE
Nodes sometimes send duplicate messages through Approval Distribution

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#2499]
Cause is unknown. Needs investigation.

**Comment by ordian** [comment]
I think there is an inherent race condition due to how gossiping works caused by the fact that we update our "view" about some peer's knownledge when we send it a message, not when it receives it, so imagine the following scenario:
* peer A imports an assignment and sends it to peer B and peer C
* peer B imports the assignment from peer A and sends it to peer C updating peer C's knowledge
* (at the same time) peer C imports the assignment from peer A and sends it to peer B, updating its knowledge
* now peer B and peer C receive duplicate assignments from each other
* the problem is amplified when we have more peers

**Comment by rphmeier** [comment]
Some subsystems have 2 separate views for each peer - 1 based on what we've sent them and 1 based on what they've sent us. We could do the same here

**Comment by ordian** [comment]
> Some subsystems have 2 separate views for each peer - 1 based on what we've sent them and 1 based on what they've sent us. We could do the same here

That could only help with not changing reputation on the first duplicate send due to a race, but doesn't prevent from sending the duplicate in the first place. Unless I misunderstood you. We still send based on what we've sent and they've sent us combined.
