### ISSUE TITLE
Availability Distribution: Consider occupied cores from last k blocks within same session

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#2513]
A Before and after of availability-recovery metrics on Kusama would be really interesting (number of `NoSuchChunk`):
https://grafana.parity-mgmt.parity.io/goto/sjkh8Upnz?orgId=1 .. currently I see 3-5 `NoSuchChunk` per second.

Discussion here: https://github.com/paritytech/polkadot/pull/2423#discussion_r580616520

This was the previous behavior before using request/response and should be reinstated. A permalink to the previous implementation can be found here: https://github.com/paritytech/polkadot/blob/c66049ddda26c9609d1a2cf23c0975a1f9677712/node/network/availability-distribution/src/lib.rs#L952 .

It is not crucial to the functioning of the network but is useful for maximizing availability and increasing throughput by increasing likelihood of peers having chunks later on.

It is important to only consider blocks within the same session, and this should recover gracefully from runtime API errors as historical state may be (but is unlikely to be) pruned.

**Comment by eskimor** [comment]
Up to 7% of requests fail due to "NoSuchChunk" [right now](https://grafana.parity-mgmt.parity.io/explore?orgId=1&left=%5B%22now-7d%22,%22now%22,%22prometheus.parity-mgmt%22,%7B%22refId%22:%22A%22,%22instant%22:true,%22range%22:true,%22exemplar%22:true,%22expr%22:%22max(rate(polkadot_parachain_availability_recovery_chunk_requests_finished%7Bchain%3D%5C%22kusama%5C%22,%20result%3D%5C%22no_such_chunk%5C%22%7D%5B1m%5D))%20%2F%20max(sum%20by%20(host)%20(rate(polkadot_parachain_availability_recovery_chunk_requests_finished%7Bchain%3D%5C%22kusama%5C%22%7D%5B1m%5D)))%22%7D,%7B%22refId%22:%22B%22,%22instant%22:true,%22range%22:true,%22exemplar%22:true,%22expr%22:%22max(rate(polkadot_parachain_availability_recovery_chunk_requests_finished%7Bchain%3D%5C%22kusama%5C%22,%20result%3D%5C%22error%5C%22%7D%5B1m%5D))%20%2F%20max(sum%20by%20(host)%20(rate(polkadot_parachain_availability_recovery_chunk_requests_finished%7Bchain%3D%5C%22kusama%5C%22%7D%5B1m%5D)))%22%7D,%7B%22refId%22:%22C%22,%22instant%22:true,%22range%22:true,%22exemplar%22:true,%22expr%22:%22max(rate(polkadot_parachain_availability_recovery_chunk_requests_finished%7Bchain%3D%5C%22kusama%5C%22,%20result%3D%5C%22timeout%5C%22%7D%5B1m%5D))%20%2F%20max(sum%20by%20(host)%20(rate(polkadot_parachain_availability_recovery_chunk_requests_finished%7Bchain%3D%5C%22kusama%5C%22%7D%5B1m%5D)))%22%7D%5D) on Kusama.

**Comment by eskimor** [comment]
![no-such-chunk](https://user-images.githubusercontent.com/1527017/157729577-84b37818-5f50-410a-9138-5bb35f91a36b.png)

Situation with fixes, still in the same range of failures.

**Comment by slumber** [comment]
> ![no-such-chunk-no-popup](https://user-images.githubusercontent.com/1527017/157730047-f22722ee-57da-4f46-9673-8b2406f254ca.png)
> 
> Situation with fixes, still in the same range of failures.

It's very likely that the source of this issue is https://github.com/paritytech/polkadot/issues/4792 and it's fixed in https://github.com/paritytech/polkadot/pull/4850 (not merged yet)
