### ISSUE TITLE
Validation peer set should probably follow block announces peer set (like grandpa)

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot#2572]
Instead of picking validators at random (as of [2538](https://github.com/paritytech/polkadot/pull/2538) we might want to consider following the block announces peer set instead. Reasoning: Better usage of resources - instead of opening yet more connections, we would re-use existing ones.

Implementation would be straight forward: Just follow `NetworkEvent::SyncConnected` and `NetworkEvent::SyncDisconnected` events.

@infinity0

**Comment by bkchr** [comment]
But the "default" peerset also contains normal nodes and we want to be sure to only have validators in the validation peer set?

**Comment by eskimor** [comment]
> But the "default" peerset also contains normal nodes and we want to be sure to only have validators in the validation peer set?

Thanks @bkchr ! I was not sure whether this is the case, this would indeed be a reason to not do that :-) This brings me to another question, do we ever verify that incoming connections on the validator peer set are indeed from validators? I don't think so ... is that a problem? I guess it is, as it opens up a DoS vector...

**Comment by infinity0** [comment]
The default peerset contains normal nodes, but this could be segregated into a non-validator vs validator part. (Most grandpa messages do not need to be passed to non-validators for example.) Having different validator peer sets for different protocols makes the connectivity of the overall network harder to reason about. It is also better to e.g. have 10-15 validator neighbours and reuse these connections for all relevant subprotocols, rather than having 10-15 neighbours for subprotocol A, then a different 10-15 neighbours for subprotocol B, etc etc, as the former option restricts the effect of bad validators - fewer neighbor validators connect to them, and so they have less influence in the network.

**Comment by eskimor** [comment]
We could filter out validator connections... but in case there are none or not enough, we would need some fallback mechanism.

With regards to effects of bad validators ... not sure I can follow. If I have more connections, I also have potentially more connections to good validators. So how is having less connections better in that particular regard?

**Comment by infinity0** [comment]
> If I have more connections, I also have potentially more connections to good validators. So how is having less connections better in that particular regard?

In the context of this issue & what I described above - you might have more connections to good validators but you're only observing a subset of their protocols, so on average this doesn't mean you're seeing more of the events in the network, than reusing the same validator set for all protocols. However for a bad validator they are also connected to more good validators, giving them more options to say inconsistent things to different sets of validators on different subprotocols, or other more subtle attacks such as slowing things down, at lower intensities to avoid reputation losses. Rather than trying to reason about each possibility individually, it's easier to just say validator neighbours are to be reused for all subprotocols.

(In the wider context, as we get closer to full bandwidth usage, increasing the number of connections also means each connection has less bandwidth available, which decreases overall network throughput.)

**Comment by eskimor** [comment]
That makes sense, thanks!

**Comment by eskimor** [comment]
We are now connected to all validators - so this is obsolete.
