### ISSUE TITLE
Statement distribution should gossip to any full node

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot#2579]
Right now, it only gossips with validators, but we also want collators to see statements.

**Comment by rphmeier** [comment]
@bkchr You worked around this or planned to, relatively recently, right?

**Comment by bkchr** [comment]
Is this again broken?

**Comment by bkchr** [comment]
I fixed this after the last rococo restart.

**Comment by bkchr** [comment]
https://github.com/paritytech/polkadot/pull/2430

**Comment by rphmeier** [comment]
Not broken, just something that we are filing. Longer term, we do want collators to learn about _other_ blocks backed by validators which are not necessarily their own, so they can already import those blocks and build upon them. 

It's also related to something you've expressed in a few different places - that collators have only a small window to actually author a block. Observing backing statements and getting an idea of which parachain block will be backed will give the collator some more time to actually build upon the block, although the `collation-generation` subsystem will only gather it later.

**Comment by rphmeier** [comment]
(re-categorizing as annoyance because the system will function without this being implemented, but we can make it better by addressing this)

**Comment by bkchr** [comment]
> Not broken, just something that we are filing. Longer term, we do want collators to learn about _other_ blocks backed by validators which are not necessarily their own, so they can already import those blocks and build upon them. 


That is already solved. Collators start to import any block that is announced with the seconded statement attached. So that is nothing they need to extra ask the relay chain for. In the end we don't have any way to request a block, for that we don't know which node has this block. 

So from the parachain side, I don't see any need to see all seconded statements.

**Comment by rphmeier** [comment]
Makes sense!

Will close this issue then.

**Comment by eskimor** [comment]
Will fix the guide then, to reflect those changed requirements.

**Comment by AlistairStewart** [comment]
> That is already solved. Collators start to import any block that is announced with the seconded statement attached. So that is nothing they need to extra ask the relay chain for. In the end we don't have any mechanism to request a block, for that we don't know any peer who has this block.
> 
> So from the parachain side, I don't see any need to see all seconded statements.

Well there may still be an issue. The next question is who announces the blocks with secondary statements attached? The backing validators? 

In the long run, we maybe don't want to just trust the backing validators or the original collator.

**Comment by bkchr** [comment]
> Well there may still be an issue. The next question is who announces the blocks with secondary statements attached? The backing validators?

No, the collator that build the block. The validators are not connected to the parachain network. It was always said that relay chain network != parachain network. And block announcement is clearly something that isn't the job of the relay chain. However, the relay chain still implicitly announces a block, by baking a candidate. 

> In the long run, we maybe don't want to just trust the backing validators or the original collator.

To announce the block or what?

**Comment by bkchr** [comment]
> (2) request erasure coded pieces from each validator.

My current plan is to implement this. We already have seen multiple times that a block got "lost" or a collator was producing blocks on its own without gossiping them (probably some connection problems).

A collator can also "loose" a block when it gets shutdown after having send the PoV to the relay chain and its database is corrupt or something. So yeah, we clearly need a way to recover these blocks.

**Comment by AlistairStewart** [comment]
> No, the collator that build the block. The validators are not connected to the parachain network. It was always said that relay chain network != parachain network. And block announcement is clearly something that isn't the job of the relay chain. However, the relay chain still implicitly announces a block, by baking a candidate.

The problem that here that the collator has an active incentive not to broadcast the block. It only helps other collators produce more blocks rather than this collator.

**Comment by bkchr** [comment]
Yeah that sounds reasonable. I'm also not entirely sure how that should work. If we start to let the backing validators to announce the blocks, I'm not sure how that should work? We could maybe extend the collator protocol to inform connected collators of a particular parachain of a seconded candidate and make them able to download the block. That would probably better, than using availability recovery (we still need this for collators, because theoretically there could still only malicious collators being connected to the validators).

**Comment by burdges** [comment]
We always want one secure path which gets covered well by debugging, tests, etc.  I always suggest building the secure path first-ish, and then making some testnet configurations only use the secure path. 

We've two censorship styles here, either collators never learn the block exists, or else collators cannot obtain the block data.

We already have one secure path for block announcements since if backed the candidate receipt appears on the relay chain which the collators all see.  Add whatever else you like, but ensure collators reading block announcements from the relay chain works.  I'd expect the relay chain to be acceptably speedy initially, but maybe announcements from backers helps when parachains employ contextual execution and/or some pipelining.

As for block data, we've two choices for the secure path, either approval checkers or availability, so doing availability reconstruction sufficeas.  We cannot trust backing checkers for the secure path since they're so few, but maybe they provide nicer performance boost.

**Comment by bkchr** [comment]
> but maybe they provide nicer performance boost.

Yeah, especially as the collators are already connected to them.

@rphmeier WDYT?
