### ISSUE TITLE
Crowdloan Lifecycle Minor Improvements

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/polkadot#2595]
A few minor quality of life improvements for Crowdloans:

- Close on win: A crowdloan is configured to be open for some duration, which could span several auctions. If a crowdloan _wins_ an auction, further contributions should not be accepted. This will prevent users from contributing after a crowdloan wins and not having their DOT/KSM reserved but nonetheless inaccessible.
- Docs on re-usability: The `index` of a crowdloan is the chain's `ParaId`, which should never change. The pallet docs should make clear that a chain must complete the crowdloan lifecycle of "create, contribute, (win, onboard,) retire, dissolve" before starting a new one. Crowdloans for bidding in auctions to extend the parachain's lease should be done outside the Relay Chain, e.g. in logic on one of the para's pallets.

CC @shawntabrizi

**Comment by crystalin** [comment]
@joepetrowski I don't fully understand the 2nd point.
I think it makes sense to have the index matching the parachain id, however, I don't understand why not allow the parachain to extend its leases using another crowdloan (by dissolving the one before the end of the previous lease, for example). 
We had the feeling that the crowdloan should be a permanent feature, not just a one-time to allow bootstrapping.

**Comment by shawntabrizi** [comment]
@crystalin there is no technical reason. Crowdloans are simply a bootstrapping mechanism and should be replaced by smart contracts and other functions.

They are intentionally not meant to be repeating, and are more simple to design because of that.

As for this issue, I believe it can be closed now as we have addressed both points in updates over the last weeks.
