### ISSUE TITLE
Allow staked assets from Polkadot and Substrate chains transferred from one wallet to another wallet without unstaking

### ISSUE THREAD

**Issue by TT1943** [paritytech/polkadot#2619]
When Polkadot launches, there is no hardware ledger support for Polkadot. This makes users have to manage the wallets by using private key. Right now, if users want to secure their assets, they have to 1. unstake 2. wait for 28 days 3. restake. The drawback of this way is that, users lose 1 month of staking reward. And also, the large amount of unstaking will affect market price.
Is it possible to create an atomic-operation to allow users transfer assets from one wallet to another in one transaction?

**Comment by Swader** [comment]
This is not possible. The system has no means of telling who owns the wallets, so this is effectively trading (transfering) or locked funds. The tokens are locked for a reason, and moving them while locked would undermine the security.

**Comment by burdges** [comment]
It's easiest if ledger adds support your old wallet's seed phrase format.  This could be done by storing some xor mask form the ledger's derived key.

We could only change keys by proving the current secret key holder possesses knowledge of the new ledger secret key, which looks roughly like
1. Old device hold old secret key x with public key X = x G.
2. Ledger derives its secret key y for public key Y = y G.
3. Foo obtains both the ledger secret key y and old secret key x.
4. Foo publishes signatures (R,c_y) and (R,s_x) by Y and X that share a common nonce R = r G.

At this point, anyone who *ever* learns x also learns y, since both (R,s_y) and (R,s_x) live on the public blockchain, and the nonces cancel out giving s_x - s_y = c_x x - c_y y.  It follows the chain could changes the staked key form X to Y but we also made your Ledger device as insecure as your old storage technique.  If however you believe your old storage never got compromised then you can simply destroy all records of the old key, and now your safe on the ledger device.

There are many nasty corners here for not much gain, so really no this sucks, and one should sinply find a way to import the old seed phrase into ledger.

**Comment by burdges** [comment]
We've another better way without doing suicidal looking nonce reuse tricks..  

We're fighting the nothing at stake problem here, so we actually merely prove the new ledger key accept the liability.  How does this work?

Alice begins owning a old stash and old controller already.  Alice first creates a new stash, and new controller key, and then her new stash certifies with it accept responsibility for the old stash.  Alice now waits 28 days so her new stash takes responsibility for everything her old stash and controller did.  At this point, polkadot could permit transfers from the old stash to the new stash.  

I've not worked out the full details but we'd want back certs by all the keys involved probably.   There are risks in this technique since people imagine you cannot move their shashes, so maybe permit the old stash orcontroller to revert the transaction within another 28 days too.

We've higher priorities so not sure this warrants the time investment anytime soon.

**Comment by shawntabrizi** [comment]
Swader is 100% correct here. Funds should NOT be transferable when they are locked up in staking. Blockchain has no way to distinguish these actions, so not gonna happen unfortunately.

**Comment by burdges** [comment]
Any two hard key derivation schemes could be made compatible as follows: 
- New device derives new secret s.
- New device blinds new secret s' = s ^ b with blinding factor b, and presents s' as a QR code.
- Old device accepts instruction to reveal its secret key k, reads QR code of s', and shows a QR code of k' = s' ^ k
- New device accepts k' and computes and stores d = k' ^ b ^ s, and possibly. 

You can omit the b if desired, and doing so lets the user back up k' meaningfully, but b helps against side channels or something.
