### ISSUE TITLE
Polkadot service requires >16GB RAM to build

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/polkadot#2706]
The `polkadot-service` crate takes a ton of resources to compile. It recently crossed a threshold where my Ubuntu 20.10 system with 12 threads and 16GB ram (not a weak system) has to do significant swapping. The build now takes over 15 min for me (just for `polkadot-service`). 

My colleague @notlesh recently observed it taking 18GB.

I understand this is a big crate that pushes Rust to its limits. I just want to track this and open a discussion of whether there are low hanging fruit that can alleviate the worst parts of it.

Related issue in cumulus: https://github.com/paritytech/cumulus/issues/175

**Comment by bkchr** [comment]
We are not developing the rust compiler. So, this issue is here wrong. Sorry

**Comment by burdges** [comment]
We'd happily fund rust compiler work that'd improve the situation, if you can pin down anything.

**Comment by andresilva** [comment]
Maybe reducing the number of threads used will reduce the required memory, but it will increase compile times.

**Comment by notlesh** [comment]
I snagged a screenshot of my machine using almost 17GB RAM while compiling a single job on polkadot @ 0c9d4c928:

![rustc_polkadot](https://user-images.githubusercontent.com/2967426/112663048-fd4fe700-8e1d-11eb-9fd6-52e8f8aadb5b.png)

I was able to observe the same memory consumption when compiling with `-j 1`.

I understand this is fundamentally beyond the scope of Polkadot, and I don't intend to demand a fix. But we're entering the territory where developers machines are becoming unusable for minutes at a time, crashing, or where compilation is simply not possible anymore.

**Comment by arkpar** [comment]
`-j` does not affect compiling a single crate. Try `export RUSTFLAGS="-C codegen-units=1"`

Regarding the issue, it's hard to figure what's causing the slowdown and memory usage exactly. I suspect this is caused by the heavy use of generics, which produce a ton of functions that choke an LLVM optimization pass. Someone with a good knowledge of the compiler could dig into this. On our side we adopting a policy to use `dyn Trait` as much as possible would help, but it is a considerable undertaking to refactor existing code for that.

**Comment by notlesh** [comment]
Interesting. I tried building with `RUSTFLAGS="-C opt-level=0` and observed it using slightly more than about 4GB at peak.
