### ISSUE TITLE
Could you please add "pub" attribute to "who" & "value" field for struct "IndividualExposure" in srml/staking?

### ISSUE THREAD

**Issue by hexinlee** [paritytech/polkadot#272]
Hi, I queried srml/staking->stakers to obtain the nominator vote details, and the struct "Exposure" was decoded succ. However, when I translated "IndividualExposure->who(AccountId)" to human readable ss58address, founding "who" & "value" fields are private.
Could you please change the attributes to "pub" for internal fields of "IndividualExposure"?
Thank you guys.

**Comment by rphmeier** [comment]
@hexinlee Unless you are making changes to the runtime itself, note that all data is available in storage and can be inspected even without the types in the runtime having public fields.

Within the runtime code, it's better to have more stuff private than not because it helps us enforce invariants about our data.
