### ISSUE TITLE
Thinking about the potential risks of parachain slots

### ISSUE THREAD

**Issue by jiangfuyao** [paritytech/polkadot#282]
### When the parachain loses the slot, It will be dangerous for a few weeks

Once have a parachain and enjoy secure sharing, When one day it fails to bid on parachain slots, it needs to summon a lot of validator nodes. The network will be unstable at the beginning, vulnerable and in danger. The failure to renew the auction slot is equivalent to being expelled from a warm home.

###  Bad parachain drives good parachain out of circulation

> "Bad money drives good money out of circulation" means: Bad parachain drives good parachain out of circulation.

If there's a giant whale, and it's a garbage project, in order to make money. By occupying slots, he wants to show leek how grand the project is. Then he can raise prices and harvest leeks.

If have one, there will have more. Because money can be made in there. If there are multiple garbage projects with huge sums of money competing for parachain, then the problem will surface. The really good projects may not have the edge in this competition.

Just like the housing prices in Beijing, which used to be bought by rich people in competition, many of them are empty now, but many locals are driven away because they cannot afford it.

Housing prices are unusually high, but few actually live there. - The slots price is being contested unusually high, but few actually use it for real value.

Both have one thing in common: they can be used for other purposes:

- The house can appreciate, decent status, symbol of wealth.
- Parachain for garbage projects can be used to create momentum, publicity, the opportunity to raise prices, harvesting leek.

### To get slots from nothing

>Get slots for free by shady means, why not to do for garbage project?

Using the slot as the news face, pulling up the price, harvesting the leek, is equivalent to earning the slot auction cost, which is equivalent to getting a slot for free, which is very cost-effective.

Just like some bad poverty alleviation institutions play ways: The fund of the funder turns around in his own hands. The last reputation, fame, awards, popularity, formal image, social status, all have. why not to do for some speculators?

### Secondary relay chain, will not ease the hype, but will increase

Because there will be overwhelming publicity: "My project has level 1 polkadot parachain slot! It's first-level, the famous xxx project is second-level!". 

Just like the mineral water inside Starbucks is expensive, it is to make customers feel that coffee is not very expensive.

The second-level slots need 5K DOTs to get, and the first-level 20K DOTs are not expensive.

### Secondary RelayChain lost slot problem

If the long running secondary RelayChain failed in the auction, it loses the slot, will  involve all of its secondary parachains. Could cause panic. There's no guarantee that every secondary parachain will have enough validators, may cause the network to be forced to stop.

**Comment by gavofyork** [comment]
We auction off the slots because so far it is the least bad, most tractable and simplest means of allocating these scarce resources. This is typical of the blockchain space. If an objectively better way of allocating the scarce resources comes along, then we'll consider it (and if it's after genesis, then it will become a community decision). So far one has not.

Governance can alleviate this, and for parachains that are strictly adding free functionality to the relay chain, for example any parachain that *does not have its own token*, is *unpermissioned* and for which any transaction fees go directly and completely to the collators, then W3F has several slots that it can bestow for free in the early years. I anticipate that Polkadot's governance will continue acting in the common interest and keep providing such "common good" parachains with slots. Examples of these would include:
- Bridges that do not have their own internal economy/token/distribution.
- Composed Polkadot relay chains *running with the same token* (relay chains that run with a different "DOT" token would not count here).
- System level components, currently placed as modules in the relay chain, that could eventually be moved to a parachain such as staking, governance and balances/indices.
- Functional additions yet to come that do not introduce additional tokens/currencies and are open/permissionless. Examples might be identity/reputation systems, stablecoin(s), scalable balance-transfer mechanisms (like Plasma cash), oracle(s) and smart contract platforms.

It is safe to say that any parachain that could reasonably be considered as independent from the relay chain (e.g. because it has its own leadership, team, founders, community, investors and/or token) would probably need to compete for a slot fairly. That said, after genesis it's the governance that decides such matters.

**Comment by jiangfuyao** [comment]
The `Parathreads` will be best way to slove these problems, which @gavofyork first proposed in Shanghai meetup.
