### ISSUE TITLE
Connection keep alive mechanism broken on key changes

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot#3038]
It seems that we keep track of connection requests by `AuthorityDiscoveryId` in [validator discovery](https://github.com/paritytech/polkadot/blob/master/node/network/bridge/src/validator_discovery.rs#L112) and we issue add/remove to peer set requests based on that [here](https://github.com/paritytech/polkadot/blob/master/node/network/bridge/src/validator_discovery.rs#L196). Problem is, if an authority changed its key at the session boundary, then different `AuthorityDiscoveryId`s would match to the same `PeerId`, resulting in the connection to be dropped, although it should be maintained.

This happens as the same `PeerId`/address would be added and removed immediately afterwards. 

@ordian is this analysis correct or am I missing something?

**Comment by ordian** [comment]
Hmm, you're right!

However, there is also another issue with key rotations. The problem is that the authority discovery cache might remove the entry for the old `AuthorityId` [link](https://github.com/paritytech/substrate/blob/17f4f08c65e4456733b750c7ceceff23be93b175/client/authority-discovery/src/worker.rs#L387), which might lead to a leak instead of removal.

**Comment by eskimor** [comment]
Right! Using the cache for anything else than the initial discovery is just racy and prone to bugs. That cache is not immutable, so we should not treat it as if it were.
