### ISSUE TITLE
Approval Voting: Continue checking even when stale

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#3253]
The current implementation of approval voting discards approval-checking background futures when the relay-chain block they correspond to is orphaned. That is, when the block is no longer possible to finalize due to a competing chain being finalized.

Although _very_ difficult to exploit, this does leave a small gap where a sophisticated attacker can take free attempts at finalizing bad parachain blocks with no dispute being raised, as all honest approval checkers may be convinced to stop checking the block. 

By continuing to check the parachain block even after it is orphaned, there is no way to avoid a dispute being raised and the backers being slashed.

**Comment by burdges** [comment]
We'd ideally want dying forks to somehow trust a better fork that includes the same candidate, but continue checking when the better fork contains a different backed candidate.  

As a simple measure, we might deprioritize but not completely stop the checks from dead forks.

**Comment by burdges** [comment]
Approach:  We ask all validators conclude all approval checks for any assignments they actually announce, like originally planned.  Although we continue, we could optionally slow down approvals work on any chains that fail being the best chain.  Importantly, we also delay making any assignment announcements until a block lives in the best chain, meaning assignments listens to fork choice.  We also delay making babe secondary blocks be the best chain slightly to give more time for receiving a primary block. 

Example:  A babe secondary block B2 appears.  All nodes see B2 but wait doing assignments because although it's now the chain head, and could become the best chain soon, we still consider its parent to be the best chain.  A babe primary block B1 appears.  All nodes see B1 and begin doing their assignments.  One slow validator Vlad thought B2 was the best chain briefly and made assignments announcements, so Vlad also makes assignments announcements on B2 and now does approvals work on both B1 and B2, but maybe slows down B2. 

Alistair and I have not worked out if a block having more assignments should be made a best chain tie breaker.  Alistair says no, but I'm not yet convinced either way.

**Comment by rphmeier** [comment]
We should defer on the fork-choice stuff until later. It's a lot of complexity we can avoid as a first step

**Comment by Lldenaurois** [comment]
Starting on this now. Seems a bit challenging so I will post a set of questions based on my research.
