### ISSUE TITLE
compact & uncompact codec CI check

### ISSUE THREAD

**Issue by GopherJ** [paritytech/polkadot#3822]
xcm Transact needs to ensure that the relaychain can decode type correctly, currently I think polkadot has already extrinsic order's CI check which is good. I'm wondering if we need something like codec compact check.

Because if the relaychain changed from `uncompact` call arguments to `compact` argument or the reverse, this can cause decode failure (if parachain didn't update)

**Comment by GopherJ** [comment]
One example will be https://github.com/paritytech/substrate/blob/master/frame/staking/src/pallet/mod.rs#L850, if someone for example changed it to `#[pallet::compact] num_slashing_spans: u32` and parachains didn't update yet. Then it can cause failure on xcm transact

**Comment by bkchr** [comment]
And then? What should happen? The transaction ordering CI check is for not forgetting to bump the `transaction_version`, but what would be the action after detecting that an argument is now compact? (While I think that this is maybe already detected by the CI check, because that changes the transaction format..) 

CC @jacogr the check is from you AFAIR? Do you already check if an argument is now compact?

**Comment by jacogr** [comment]
No sure where the JS API sits atm - the xcm rapid changes has been brutal, so there is bound to be fallout.

**Comment by bkchr** [comment]
@jacogr No, I was speaking about your js code to compare two runtime versions to check if a transaction was changed.

**Comment by jacogr** [comment]
Ahh, ok, misunderstood. Indeed, for the metadata compare the types of the arguments in the extrinsic are being compared. So if it goes from non-compact to compact, it will be logged as part of the CI check.

**Comment by bkchr** [comment]
Sounds to me like we can close this issue.

**Comment by GopherJ** [comment]
@bkchr @jacogr thanks understood!
