### ISSUE TITLE
Metric on recent disputes

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot#4326]
The number of recent disputes (+vote count in each of them) can become large in cases of spam. It would be good to know how many votes/disputes the block producer has to process on each `create_inherent` call.

**Comment by rphmeier** [comment]
If we do find that too many statements are overwhelming the runtime, we have a few possibilities:
1. Surface-level patch: Switch from using `RecentDisputes` to `ActiveDisputes` in the provisioner. However, we might need to extend the "active" timer because if no honest node authors a block for 5 minutes after something is concluded, then it might never land on-chain. I say 5 minutes because that's the amount of time it takes for something to no longer be considered active once concluded.
2. Deeper patch: Make the provisioner and dispute coordinator smarter about what it submits to the runtime to avoid submitting long-settled disputes every time.
3. Alternately: Make the runtime filtering way faster.
