### ISSUE TITLE
BuyExecution return assets to Holding in case of error

### ISSUE THREAD

**Issue by girazoki** [paritytech/polkadot#4507]
I am testing a scenario in which I receive a message of type WithdrawAsset | ClearOrigin | BuyExecution | DepositAsset. Specifically I am testing the case in which the BuyExecution fails because the payment is insufficient (TooExpensive error). As far as I can tell, an error in _self.trader.buy_weight(weight, max_fee)?;_ is directly returned and the taken amount for fees is never refunded to the HoldingRegister. This makes these assets not be trappable in _post_execute_. Is this something expected?

![image](https://user-images.githubusercontent.com/18615930/145589286-6c727b1c-281f-4eff-9e95-6d7f79227a1e.png)

**Comment by KiChjang** [comment]
We could in fact match against the error returned by the `WeightTrader` and see if it's `TooExpensive`, and if so, put the `max_fee` back into holding. However, this would open an attack vector where an adversary can simply send a lot of XCMs containing `BuyExecution`s that have less than the amount of fees required to pay for the weights, and make the XCM executor work "for free", essentially DDoS'ing the executor.

Setting aside from the possible attack scenario, it's also unknowable to the executor whether or not the `WeightTrader` has already taken some fees when producing the `TooExpensive` error. If we simply put the `max_fee` back into holding, we may have then erroneously increased the total issuance of the assets.

Owing to the above, putting assets that did not have the required amounts to pay for execution back into the holding register is a dangerous idea, and halting XCM execution is the correct behaviour.

I do understand though that in the common case, you'll want to have a way to keep track of the insufficient fees. However this wouldn't be the responsibility of the XCM executor -- it will be the `WeightTrader`'s responsibility. Since it is a configurable parameter, you could in fact write custom logic to handle such kinds of behaviour, or even write a pallet for it.

**Comment by girazoki** [comment]
That seems reasonable, thanks a ton for the response. It is indeed a concern if we dont track the fees related to insufficient payments as this poses a big UI challenge (users need to know exactly whats the minimum amount they can send so that the `WeightTrader` accepts it). We will think about solutions for handling those kind of scenarios.
