### ISSUE TITLE
runtime/session-info: use `Executive` for migration

### ISSUE THREAD

**Issue by ordian** [paritytech/polkadot#4715]
@kianenigma brought this to my attention:

We're using a deprecated mechanism for runtime migration in session-info:
https://github.com/paritytech/polkadot/blob/b4dcb305278e3930c2d8e1d580aa1cddf51deb9d/runtime/parachains/src/session_info.rs#L77-L82

instead, we should do something like https://github.com/paritytech/polkadot/pull/4710/files.
It would be good to write some pre/post-conditions as well, e.g. ensuring the length of `Sessions` is preserved.

This is also true for the Configuration pallet.

**Comment by bkchr** [comment]
While @kianenigma is right, for concrete blockchain implementations I don't see such a huge need for putting everything into the runtime lib.rs file. The point being here is that this stuff isn't reused by others and they are not getting fucked that easily. For migrations in Polkadot it is completly okay to remove them after they are applied on chain, because they will never be required anymore.

**Comment by ordian** [comment]
I guess the main benefit is being able to test with try-runtime and writing down the migration invariants explicitly.

**Comment by bkchr** [comment]
Try runtime also works on pallet level.

**Comment by kianenigma** [comment]
Yes try-runtime works for both. 

While Basti's argument is correct, I think it will still make life easier for everyone if we stick to doing migrations via the top level runtime only. At the minimum, it makes it a few clicks easier to track which migration went into which release. 

That being said, i don't think this needs an issue. If this is already release/deployed, then too late. Else, we can only change it until the next release, so better make a PR directly rather than an issue that could get lost :p

**Comment by ordian** [comment]
> If this is already release/deployed, then too late

I believe it will be released in 0.9.16, which is not cut yet.
I opened this issue as a good-first-issue for new joiners.

**Comment by ECJ222** [comment]
Can I take on this issue?

**Comment by ordian** [comment]
> Can I take on this issue?

please do!

**Comment by ECJ222** [comment]
Hi @ordian,

Please could you write a short description of this issue?

**Comment by ordian** [comment]
I'm going to close the issue, because we already branched off for the next release and it doesn't make sense to change it in the version after next because the migration will not run anymore.
