### ISSUE TITLE
Key reported by the node does not match the seed

### ISSUE THREAD

**Issue by chevdor** [paritytech/polkadot#474]
# Working

- Seed: `0x1`
- Address: `5GqhgbUd2S9uc5Tm7hWhw29Tw2jBnuHshmTV1fDF4V1w3G2z`

Running 
`polkadot-0.2.1 --validator --key 0x1` 
it says 
`Using authority key 5GqhgbUd2S9uc5Tm7hWhw29Tw2jBnuHshmTV1fDF4V1w3G2z`

# Not working

Using https://poc-2.polkadot.io/#/accounts, create an account.
- Seed: `0xbcb031a6105cbbfcfb34fe3efe7561b1e38d7bbed3f582b47540be18e4f3fbf9`
- Address: `5HUGeK7PVfwbrcdGiaetMfsdSi6QWQYy2QLKkSGdBHTdK6pk`

Running 
`polkadot-0.2.1 --validator --key 0xbcb031a6105cbbfcfb34fe3efe7561b1e38d7bbed3f582b47540be18e4f3fbf9` 
it says 
`Using authority key 5CFch3NtzbZwiaN9ibGWQdsroT5duVPF8Q2X8nQRiASF8bkE`

=> the key does not match

**Comment by chevdor** [comment]
I suspect this is the issue that caused many validators to be slashed. I created a new account with a shorter string seed, checked that the address matches when starting the client and since, I am validating properly.

**Comment by jacogr** [comment]
Not sure where this issue lies, but seems to be a mismatch in how the Node and UI treats the hex and what it does. 

So UI-wise this is what happens, 

`abcdefghijklmnopqrstuvwxyzABCDEF` -
5F5qLWzvaPySYio7EbmwDPkGPaXScm1nVxYgDxgwFFSYxx3F

Taking the hex string as-is and converting to hex via https://codebeautify.org/string-hex-converter -

`0x6162636465666768696a6b6c6d6e6f707172737475767778797a414243444546` -
5F5qLWzvaPySYio7EbmwDPkGPaXScm1nVxYgDxgwFFSYxx3F

On the node, running with `--validator --key ...` -

`abcdefghijklmnopqrstuvwxyzABCDEF` -
5F5qLWzvaPySYio7EbmwDPkGPaXScm1nVxYgDxgwFFSYxx3F

`0x6162636465666768696a6b6c6d6e6f707172737475767778797a414243444546` -
5FjuPW1zb2wc35wiLc9oNeH4ZW3Wq5McTah7c1AMvX6sYcAb

So the UI takes the hex as-is, converts to bytes and uses that as the seed. It could be -

1. The UI/Node has a mismatch in how it creates the keys (i.e. both not just using the value as-is)
2. The UI/Node has a mismatch in how it interprets/formats the hex string (UI simply takes fist value, puts in in slot 0, 2nd value in slot 1, ...)
