### ISSUE TITLE
Integrate networking with consensus protocol

### ISSUE THREAD

**Issue by gavofyork** [paritytech/polkadot#50]

**Comment by rphmeier** [comment]
We discussed this when the issue was created -- there is actually a fair bit of work to be done in terms of "integration", and only some of it is relevant to networking:
  - input and output channels to the other validators
  - stream of empty statement buffers (controlled by network so it can set the target validators)
  - fetching candidate block-data and auxiliary data to check validity and availability

The rest of the work involves integration with the state:
  - determination of roles taken by validators (in terms of grouping and primary selection)
  - fetching of local parachain candidate (we can skip this for PoC-1)
  - creation of a relay chain block from candidates with enough requisite votes
  - verification that the candidates in a proposed block have enough requisite votes

**Comment by gavofyork** [comment]
for substrate (poc-1) we don't need to be concerned with parachains.

for the relay chain block, we can probably just have a rotating validator propose it, no?

**Comment by gavofyork** [comment]
#54
