### ISSUE TITLE
Test `terminates_on_timeout` fails with latest Substrate

### ISSUE THREAD

**Issue by bkchr** [paritytech/polkadot#5190]
The test is failing with:

```
thread 'terminates_on_timeout' panicked at 'Err(InvalidCandidate(WorkerReportedError("execute: Allocator ran out of space")))', node/core/pvf/tests/it/main.rs:98:14
```

https://gitlab.parity.io/parity/polkadot/-/jobs/1457003

The heap base is being fetched as the maximum memory size given to the runtime. I think this is related of us using the default allocator and not overwriting the allocator as we do for our runtimes.

Can be reproduced by:
```
cargo update -p sp-io
cargo test -p polkadot-node-core-pvf --release terminates_on_timeout
```

**Comment by koute** [comment]
I'm on it.

**Comment by koute** [comment]
Okay, so the problem here is that the PVF executor expects an extra 2048 heap pages allocated which it is not getting, hence the allocator is running out of space.

Since my PR those extra heap pages are not added during the instantiation but are statically added to the WASM blob before it is compiled, and the PVF executor precompiles its WASM blob, and that codepath *doesn't* add those extra heap pages, so it only allocates whatever is originally requested by the WASM blob itself.

Should be an easy fix; I'll also add a test to `substrate` for this while I'm at it. I'll have a PR with the fix ready tomorrow.

**Comment by fig666** [comment]
@koute so the specific time of replying use of knowledge without any key string errors while compiling summarization of input data for comprehensive language skills? i understand but keep getting blockchained during indicating a response based off device operating system dynamics reiterating complete function of use
