### ISSUE TITLE
Support multiple slots auction at same time.

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot#534]
Currently the `slots` module only support one auction at time and one slot per auction. This have few issues:

- It is slow.
- Polkadot is going to have >50 slots for auction. Without the ability to support auction multiple slots at same time, the auction duration for each slot on average cannot be more than 365 * 2 / 50 = 14.6 days. This limits the maximum duration for each auction.
- It will be unfair. A fair auction process should incentive everyone to place their maximum willing bids upfront. But I don't think knowing there will be multiple slot auctions after current one will incentive people to place their maximum bid on the first auction.

Any reason to not support multiple item action? A possible explanation is the computation complexity may make it too much work to be computed on-chain. But this can be easily delegated to off chain computation by allowing people to compute optimal result off-chain and submit it online. Give it a day or two for people to challenge the result should be enough (winners are going to have big enough incentive to submit optimal result).

**Comment by gavofyork** [comment]
It was sufficiently non-trivial that W3F research didn't attempt a design. Feel free to have a go yourself though, just ensure that you can prove it's fair.

**Comment by burdges** [comment]
I personally kinda expected parathreads would remove any need for parallel slot auctions, not sure whatever everyone else thought.  If this actually sounds like a priority then we could discuss it further.  I'd expect parallel slot auctions would give us a nicer notion of second price, which improves things.  cc @AlfonsoCev

**Comment by AlfonsoCev** [comment]
Some reasons for auctioning one parachain slot at a time are price stability and price discovery. In the extreme case where we auction a bunch of slots only once a year, there would be a pump in the price of DOT relative to USD because of all the bidders buying DOTs, with an ensuing dump afterwards, and it would be very difficult for bidders to predict how much they need to win a slot, since so much time has passed from the last auction. Both factors affect the perceived risk of becoming a parachain. 

So my intuition is that it's better to take the opposite route and have one slot (or very few slots) auctioned every couple of weeks or months. That way there is no "auctioning season" so the liquidity of DOTs will be more stable, and the value of the winning bids will stabilize so prospective parachains can plan better.

**Comment by xlc** [comment]
Seems like this is not happening and that's fine.
