### ISSUE TITLE
pvf-host wasm module keeps spawned despite being not actively (para)validating

### ISSUE THREAD

**Issue by stakeworld** [paritytech/polkadot#5726]
- kernel: 5.4.0-113-generic 127-Ubuntu SMP Wed May 18 14:30:56 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- default ubuntu 20.04 LTS generic install
- polkadot 0.9.24-22836e55d41 from parity apt-repository
- dedicated AMD Ryzen 5 3600 Machine

When getting in an active paravalidating session polkadot spawns "pvf-host" apparently for the "Parachain Validation Function" which is a "wasm module" used in parachain validating. 

I've noticed that when leaving the parachain validating and even going out of the active set the processes keep spawned and are using resources. A restart of the node stop's the extra spawned hosts and brings everything back to "normal"

I'm not 100% sure it it is a bug but my expected behaviour would be that when not actively paravalidating the pvf-host would be killed and respawned when needed.

Below a part of `systemctl status` on a non active node.
![image](https://user-images.githubusercontent.com/106294967/175468412-cb9437ce-9c88-43f0-a8ee-c10a305aa452.png)

**Comment by bkchr** [comment]
CC @pepyakin

**Comment by pepyakin** [comment]
Right, the worker processes are never released currently. It's not the end of the world, since I expect those processes to be dormant. That means that they don't consume CPU[^1] and the memory they reserved should eventually be swapped[^1]. That said, I think there is little reason for keeping them around either. It would be ok to shut them down after some period of time.

[^1]: that does not account for the kernel resources, but that should be pretty minimal.

**Comment by stakeworld** [comment]
Thanks for the feedback. I've examined the processes and indeed they don't seem to take resources while dormant.

`# pidstat -p 150232
07:59:55 AM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
07:59:55 AM   107    150232    0.00    0.00    0.00    0.00    0.00     7  polkadot`

@pepyakin should I make it a feature request or is it something not worth the trouble and just close?

**Comment by pepyakin** [comment]
I think it is not necessary, let's keep this one for tracking.
