### ISSUE TITLE
Maybe missing components for crowdloan benchmarks

### ISSUE THREAD

**Issue by Chralt98** [paritytech/polkadot#5928]
https://github.com/paritytech/polkadot/blob/c3d5882a64e5330a04d9b2486891e30ac9c58768/runtime/common/src/crowdloan/mod.rs#L1994-L2025

The benchmark logic of `withdraw` assumes, that there is no component which affects the weights (processing time) of the dispatch function.

https://github.com/paritytech/polkadot/blob/c3d5882a64e5330a04d9b2486891e30ac9c58768/runtime/common/src/crowdloan/mod.rs#L487

`contribution_get` is a query of a child tree element. I thought, that child trees have a O(log(n)) query time. Shouldn't be the amount of contributions affect the processing time of the `withdraw` function as a benchmark component?

**Comment by ggwpez** [comment]
We already benchmark the storage access times with a full snapshot, so it is always using worst case ([+10%](https://github.com/paritytech/polkadot/blob/c3d5882a64e5330a04d9b2486891e30ac9c58768/runtime/polkadot/constants/src/weights/paritydb_weights.rs#L48)) for storage access.  
It would be problematic if there is a loop in the code itself, eg. a `search` function.  
Storage accesses are a special thing; we factor them out in the resulting weights.  
The withdraw weight looks like this:  
```rust
fn withdraw() -> Weight {
	(52_784_000 as Weight)
		.saturating_add(T::DbWeight::get().reads(4 as Weight))
		.saturating_add(T::DbWeight::get().writes(4 as Weight))
}
```
It is necessary since we support multiple DB backend with different weights per READ/WRITE.  

I will add a note to the SE answer yesterday to include this.
