### ISSUE TITLE
Parachain upgrade on Rococo failed due to PVF timeout

### ISSUE THREAD

**Issue by Dinonard** [paritytech/polkadot#5972]
Hello,

I attempted to upgrade Astar's Rococo cousin `RocStar` today but it silently failed or didn't happen.

Overview of what happend:
* Scheduled an upgrade on RocStar (chain Id **2006**), validation function was stored
* Delay is 100 relay chain blocks
* That time passed but no upgrade happend
* On RocStar, `PendingValidationCode` storage is still set
* On Rococo, there are no pending upgrades for RocStar
* RocStar is still producing blocks normally (using old runtime)

Event on Rococo which originated from scheduling the upgrade is [here](https://rococo.subscan.io/extrinsic/1811864-1?event=1811864-3).

Current RocStar is `astar-22` which is based `polkadot-v0.9.24`. The one I used to upgrade is `astar-33` which is based on `polkadot-v0.9.28`. Since active Rococo runtime is based on `polkadot-v0.9.25`, could this cause problems?

If this isn't the right place to raise the issue, please point me where it is :pray:. Thanks!

> Endpoint for RocStar: wss://rocstar.astar.network

**Comment by rphmeier** [comment]
https://rococo.subscan.io/extrinsic/1812726-0?event=1812726-28

It looks like the PVF check for the was rejected, which is either due to timeout (occurs in a new session) or explicit rejection. In this case, it looks like a time-out, because https://rococo.subscan.io/block/1812726?tab=event is the first block of a new session.

Not sure why this is timing out, though - validators should be participating in the PVF checks. The runtime should be attempted again and may succeed.

**Comment by eskimor** [comment]
Are all validators upgraded to a recent enough binary?

**Comment by Dinonard** [comment]
I tried again but nothing happened.

Seems it's an issue for everyone in the last 24h according to [this](https://rococo.subscan.io/event?address=&module=paras&event=all&startDate=&endDate=&startBlock=&endBlock=&timeType=date&version=9250). Lots of rejects.

No voting seems to happen at all.
![pfv](https://user-images.githubusercontent.com/3002868/188852295-5a5c4598-2843-499b-a990-ed7c72ce30b9.png)

**Comment by slumber** [comment]
@Dinonard it happened due to testing attempt to enable PVF prechecking, since all validators have this feature disabled on the node side, every upgrade simply gets timed out and rejected.

https://rococo.subscan.io/extrinsic/1827032-2

Once the configuration is updated on the next session change please try again

**Comment by Dinonard** [comment]
@slumber just to confirm, I've successfully upgraded RocStar.

Thanks all for the help!
