### ISSUE TITLE
`approval-voting`: Add missing traces

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot#6044]
Grafana Tempo might actually be [working](https://grafana.parity-mgmt.parity.io/goto/k-K5lynVk?orgId=1), what seems to be missing is traces in various subsystems. It would be good to add those soon, so we can have proper traces in the next debugging session.

**Comment by sandreim** [comment]
A good start would be `approval-voting`. 

We have spans for handling activated leaves `approval-checking-import`, `approved-ancestor` calls, `process-approval-wakeup`, and `launch-approval` but we don't get too see all of them in a single view because we are using different identifiers (relay hash, candidate hash, expected_tick, or combinations of these). It is cumbersome at least from Grafna Tempo to have different queries to look at things. 

To get a more consolidated view we need to implement the following (non-exhaustive):
- move spans into per-leaf child spans in to see how much work we are doing per relay block. We would still need to do a separate query if we want to look a specific candidate.
- adding a child span for assignment imports and nest each import spans under these to observe delay tranches
- make launch-approval a child span and ensure it fully covers the operation (currently misses 2 other subsystem calls)
