### ISSUE TITLE
AllowTopLevelPaidExecutionFrom incorrectly checks Limited weight in BuyExecution

### ISSUE THREAD

**Issue by Dinonard** [paritytech/polkadot#6067]
Hi,

In `AllowTopLevelPaidExecutionFrom` ([here](https://github.com/paritytech/polkadot/blob/1cbab5a698eb65675f8cbb7632033716159fe741/xcm/xcm-builder/src/barriers.rs#L83)), when processing `BuyExecution` we do it like this:
```Rust
BuyExecution { weight_limit: Limited(ref mut weight), .. } if *weight >= max_weight => {   <==== THIS CHECK
		*weight = max_weight;
		Ok(())
	},
	BuyExecution { ref mut weight_limit, .. } if weight_limit == &Unlimited => {
		*weight_limit = Limited(max_weight);
		Ok(())
	},
	_ => Err(()),
}
```

Regarding the first arm, should we also be `Ok(())` in case `weight` is below `max_weight`?

It seems like an error to me but I'm skeptical of my own understanding since it hasn't been noticed by now :sweat_smile:

**Comment by KiChjang** [comment]
No, because recall that whatever you specify as `weight` in `BuyExecution` is the _total amount of weight that your XCM is willing to pay for_. If it's any less than `max_weight` (which I know is a misnomer, but it means what the executing chain thinks is fair price for the message), then we should definitely throw an error and refuse to execute the said XCM, as it did not pay enough weight.

**Comment by Dinonard** [comment]
You are right, my mistake! This makes total sense, I switched the order in which `Transact` and `BuyExecution` are evaluated when thinking about it.

Following everything that happens can get confusing :sweat_smile: 

Closing the issue.
