### ISSUE TITLE
[Rococo chain]: fail call mmr.generateProof: MmrLeafBatchProof and beefy.getFinalizedHead: H256

### ISSUE THREAD

**Issue by DaviRain-Su** [paritytech/polkadot#6648]

**Comment by bkchr** [comment]
CC @acatangiu

**Comment by acatangiu** [comment]
> fail call mmr.generateProof: MmrLeafBatchProof

Following https://github.com/paritytech/devops/issues/2287 - the MMR was reset so the leaf indices are no longer in sync with block numbers - I am guessing that's what's failing for you.

We probably should add some translation code at the RPC level, so API works with block numbers instead of leaf indices?

**Comment by acatangiu** [comment]
> fail call beefy.getFinalizedHead

Deployment of "Full BEEFY" over live/running "Lean BEEFY" failed - more details in https://github.com/paritytech/devops/issues/2198.

BEEFY is currently disabled on Rococo, will be re-enabled after fixing https://github.com/paritytech/substrate/issues/13156 to allow clean deployment of Full BEEFY.

**Comment by acatangiu** [comment]
> > fail call mmr.generateProof: MmrLeafBatchProof
> 
> Following [paritytech/devops#2287](https://github.com/paritytech/devops/issues/2287) - the MMR was reset so the leaf indices are no longer in sync with block numbers - I am guessing that's what's failing for you.
> 
> We probably should add some translation code at the RPC level, so API works with block numbers instead of leaf indices?

It seems this just needs a runtime upgrade, because RPC code is now using different API, while runtime is still old version with old api (we haven't done api versioning still this hasn't been released yet anyway)

**Comment by Lederstrumpf** [comment]
I tested this with best blocks that are prior to the storage reset and also had proof generation failures - this is indeed unrelated to storage reset.

We have to perform a runtime upgrade  for `9380` since it will include https://github.com/paritytech/polkadot/pull/6577 (see https://github.com/paritytech/devops/issues/2287 for details) and then reset MMR storage again anyway, so we can avoid doing this twice by waiting for that release.

**Comment by DaviRain-Su** [comment]
```bash
echo '{"id":1,"jsonrpc":"2.0","method":"mmr_generateProof","params":[[4007966,4007967,4007968]]}' |  websocat -n1 -B 99999999 wss://rococo-rpc.polkadot.io | jq
```
{
  "jsonrpc": "2.0",
  "result": {
    "blockHash": "0xe102d7f6ba4ab47377159e666f80c6f01244ad1096a7c8339480497935ac712a",
    "leaves": "0x0cc501001d283d00d6bfb177ba2da1ddc85cdb59fbf217823936d72f7ddc7cf9f1d7925fb5c482c4c01a00000000000067000000404ee469d464d2b306ccf0fcc5434b72128438573f3dbd60b2a858dfdc604c23ba2e764cbb91d00a30652680c87efdc9d62b923e327f2d26665d1fbfae6c996fc501001e283d00275d28e6255613f363c16276b9943cb747d68ca51fc6517955207a177a927926c01a00000000000067000000404ee469d464d2b306ccf0fcc5434b72128438573f3dbd60b2a858dfdc604c23da02014a22a002f0a227a47f5e327ff21ac3481212afbb9a5ed4ee322434f096c501001f283d009f9b54764977f597386488b8f594ac982f6384b1a54adeb9bb71c24f144dfaa8c01a00000000000067000000404ee469d464d2b306ccf0fcc5434b72128438573f3dbd60b2a858dfdc604c23a34f4fda00d2f66be85029eac144b1a05803d0444de017d4bb72c9e9299441cc",
    "proof": "0x0ca11c030000000000a21c030000000000a31c030000000000761d0300000000003429b9496fec4860eef71c045efd02b81a4ee82c48a82dd58a89bb922f4aca1bda58a301c4957e0833406cffbb1d0e7eb5ccf53c652986784a0c22b042c5eaafd7272aab0fd0c3847705699e5a9da1ed7c54a4300c9428c84880bf10a5aaaca0bf63e72001c09b668338e705e1e65d0cac8f98bee6b96f77c3f57ab127fe1f7aea6cbb7bb344df9a81989dd3aef6d8dbdfdc198239786b3b9498ebcbc3b985700a7f3a5ea357c6d089112c54127d615b823af96ffafd68f00576668224b0ad48de7199b692b2e8457dfe91f1c16eaa5d4bccc79b1a4165d5885aefd6b8b70a4635d0ae76860d343d83ef1f63e99d9c4ec7d2c9351b3078ca1a7e7144944cdeda58dd9f17a6875a290895bb6604cc05e5b716df5e86f7430d61d6711475aa41f61502f1ccedb8e6ecaf36c390d88e43f621629a46c8ba44526614e256125c53dfdb5612b9e4ca1bea503c207a6b0492c6697799c33db8388335f07b46ef81a2a930b5eb70a6f5f4ec07a90a36e4bc743940dd6c2be3bfd56a1297dd7b2c113039ced32ab51fcff5ad444d46dea04bb87161dbc5276a60acbcceaf72dda5a544ea7a"
  },
  "id": 1
}

I use this command can get reponse.

**Comment by DaviRain-Su** [comment]
<img width="849" alt="截屏2023-02-13 11 14 40" src="https://user-images.githubusercontent.com/53282030/218362319-9ec91097-7ba9-48aa-a245-e75609c26c73.png">

rpc call beef getFinalizedHead aslo have problem.

**Comment by Lederstrumpf** [comment]
Using a local rococo-dev chain with BEEFY enabled, I've verified both issues are fixed since the deployment of https://github.com/polkadot-js/api/pull/5479. The MMR calls work on rococo too.
`beefy.getFinalizedHead` still fails since it's disabled on rococo for now, but we're tracking that separately [here](https://github.com/paritytech/parity-bridges-common/issues/1632) (under _- [ ] deploy Polkadot v0.9.41 when it comes out and enable --beefy_), hence closing this issue.
