### ISSUE TITLE
overseer: signal completion of major sync

### ISSUE THREAD

**Issue by ordian** [paritytech/polkadot#6694]
The idea is to use a sync oracle in the overseer similar to https://github.com/paritytech/polkadot/pull/6691 and either add a separate `InitialSyncComplete` signal [here](https://github.com/paritytech/polkadot/blob/713afcd96ea652a446ade5e7126414fcd7aa5220/node/subsystem-types/src/lib.rs#L140), or add a bool `is_major_syncing` to `ActiveLeaves` and `BlockFinalized` signals.

Approval-voting deliberately made a choice to only track initial major sync. That is if a node is synced, but then goes offline or is slow somehow and major syncs again, it will not detect/react to that. To be consistent with this logic, a separate signal approach would be preferred.

Another consideration: some subsystems are awaiting on the first activated leaf. If for some reason block production stalls and a node restarts, it will not import new blocks. To address that concern, we send active leaves signal on startup based on the current db state [here](https://github.com/paritytech/polkadot/blob/713afcd96ea652a446ade5e7126414fcd7aa5220/node/overseer/src/lib.rs#L731). Consider merging `InitialSyncComplete` and the initial leaves into one signal to simplify logic, i.e. adding `InitialSyncComplete(ActiveLeaves)`, where the active leaves would be fetched from either the db or the latest imported block depending on whether we major sync on startup.

**Comment by bkchr** [comment]
https://github.com/paritytech/polkadot/pull/6689 this pr already goes a little bit into this direction.

**Comment by tdimitrov** [comment]
I stumbled upon this problem while investigating https://github.com/paritytech/polkadot/issues/5885. I think most of the 'state discarded' errors mentioned there are caused by doing work during sync.

https://github.com/paritytech/polkadot/pull/6689 was supposed to be my secret 'test on versi' PR but it's gaining popularity now :) For the moment I just try to delay `ActiveLeavesUpdate` there and it seems not to cause any side effects (for now). But this is not the best solution.

For now I think the best approach might be not to change any events logic. Meaning we'll broadcast initial `ActiveLeavesUpdate` with the heads from db and we'll broadcast `BlockFinalized` events during sync. But once the sync completes - we'll broadcast `InitialSyncComplete`. It will serve as an indication for the subsystems that they can start working with the runtime.

I see two benefits for this:
1. There is a clear indication when the system is in sync and runtime calls will work as expected.
2. Subsystems receive data in advance and can do work in advance, if they decide to and it is safe to (of course this is up to the developer).

I'm not completely rejecting the other approaches though. As @ordian said we can also:
1. Add flag to `ActiveLeavesUpdate`, which has got all the benefits listed above (and no drawbacks).
2. Don't broadcast any signals until initial sync is complete.

**Comment by tdimitrov** [comment]
https://github.com/paritytech/polkadot/pull/6689 is ready for a first iteration of reviews.

What's done in nutshell:
* No `ActiveLeaves` and `BlockFinalized` events are generated until full initial sync is complete.
* No new events or flags are generated.

@ordian requested not to send any `BlockFinalized` events during sync so in this case I think there is no benefit in introducing new events.

What do you think about this approach?
