### ISSUE TITLE
Replace `RollingSessionWindow` with existing `RuntimeInfo` cache

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot#6812]
`RollingSessionWindow` keeps causing issues.

Instead of just requesting (and caching) sessions based on a given relay parent (usually of some candidate), we just grow a session window based on active leaves updates. This mechanism proved to be less reliable. In particular for example on startup we will be requesting the older sessions of the window based on a head that is in a much younger session. While in theory this should work, it does not always because of runtime upgrades and migrations/timing (bugs).

Contrary, with the classic approach of requesting sessions based on a relay parent in that very session, we don't even need the runtime to support queries of historic sessions. The only downside is that this only works for non finalized blocks, but we also only care for non-finalized blocks. In addition the query will very likely be cached by the runtime-api subsystem so it usually will even work for already finalized blocks.

Another reason the rolling session window is more fragile is that the window needs to be continuous, it does not support holes - hence if a single session fetch fails, none will be retrievable -> it will not [try fetching more recent sessions](https://github.com/paritytech/polkadot/blob/dfa8c5ae321e0523f88fdc43afc6d743812ee49e/node/subsystem-util/src/rolling_session_window.rs#L545) (which are usually more relevant) if fetching of an older one fails for some reason.

In order to make sure the cache is populated in case we need it in disputes, we could increase the [lru cache size](https://github.com/paritytech/polkadot/blob/dfa8c5ae321e0523f88fdc43afc6d743812ee49e/node/subsystem-util/src/runtime/mod.rs#L69)  of `RuntimeInfo` to 6 and just query the current `SessionInfo` from the cache on each active leaf update. This way we would keep the behavior of pro-actively caching sessions, to boost reliability even more (at the cost of some constant overhead).

**Comment by tdimitrov** [comment]
Browsing the `RollingSessionWindow` code I saw this:
https://github.com/paritytech/polkadot/blob/e9bf067c68e806cdb272e0ce8065faa543cc0b5a/node/subsystem-util/src/rolling_session_window.rs#L245

https://github.com/paritytech/polkadot/issues/6144 and this issue are related.

**Comment by sandreim** [comment]
We can close that one as well if we remove it :P

**Comment by tdimitrov** [comment]
Small update on why this is taking so much time.

https://github.com/paritytech/polkadot/pull/6968 removes `RollingSessionWindow` from `dispute-coordinator`. I'll do one final burn-in and it can be merged. 

I tried to apply the same approach to `approval-voting` but it's not looking good there. `session_window` is kept in [`State`](https://github.com/paritytech/polkadot/blob/cea4f8a8b975b44dd46b5c9b8315393d95b6b7b1/node/core/approval-voting/src/lib.rs#L641) which is intended to be immutable. Putting `RuntimeInfo` there will break its immutability because each session look up might perform caching as a side effect and requires `&mut self`. 

On top of it a lot of functions should be made `async` and should accept additional `SubsystemSender` parameter. This as big problem as the immutability but I want to avoid changing the subsystem too much (if possible).

My plan for now is to add yet another session cache to `State` which keeps its immutability. It will be updated only during leaf updates and if we fail to cache a session there it will be considered unavailable in the rest of the code. This looks fine on first sight but also I might be missing something.

**Comment by tdimitrov** [comment]
> With a little refactor better solutions should be possible as well, but I understand if you don't want to touch to much for this task.

No, if it's fine to rework the code a little bit to fit in the `RuntimeInfo` - I'll do it.
