### ISSUE TITLE
same transaction continuously failed in different blocks after it successfully packaged into block

### ISSUE THREAD

**Issue by alexxuyang** [paritytech/polkadot#689]
Our custody system broadcast one transaction and it successfully packaged into block [160391](https://polkascan.io/pre/kusama-cc3/block/160391), successful [transaction](https://polkascan.io/pre/kusama-cc3/transaction/0x3a6ebc6e415a8c7e483a78eaf84f1958e2df8e9702092a331338794eb3d1e329) in 160391.

However, we found that there are many **failed** tx after that block with the **same** txid, sender, recipient and amount. 
In [201026](https://polkascan.io/pre/kusama-cc3/block/201026) we found total 40 **same** failed tx. Same pattern existed in [194753](https://polkascan.io/pre/kusama-cc3/block/194753), and [194444](https://polkascan.io/pre/kusama-cc3/block/194444).

**Comment by alexxuyang** [comment]
BTW, we are using the kusama CC3 network.

**Comment by btspoony** [comment]
btw, i guess the reason is transfer amount is under 0.01 KSM.

Related Address: 
https://polkascan.io/pre/kusama-cc3/account/HKws3BooCyntHo3ywiaLwuZexQEwwjEUHmW3riJGP8VG9PC#transfers

two issued transfer tx (succeed):

No. | Block | Amount | Txid
-- | ---- | ------- | --------------
1 | 190160 |  0.009396250326 KSM | 0x12b0cb17f72fb0e4a9baa40fec945c06fffa3f888294918ccf9045fb21e8f8ac
2 | 160391 |  0.00879098348 KSM | 0x3a6ebc6e415a8c7e483a78eaf84f1958e2df8e9702092a331338794eb3d1e329

**Comment by bkchr** [comment]
Is this solved?

**Comment by rphmeier** [comment]
stale
