### ISSUE TITLE
how about locked/reserved funds in old gov?

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot#6992]
how about locked/reserved funds?

_Originally posted by @xlc in https://github.com/paritytech/polkadot/issues/6977#issuecomment-1492582772_

**Comment by bkchr** [comment]
CC @kianenigma

**Comment by liamaharon** [comment]
I think it might make sense to combine this issue into the one for removing storage (https://github.com/paritytech/polkadot/issues/6749) because they are very closely related. In a single runtime upgrade we could

1. Handle locked/reserved assets from Gov V1
2. Remove Gov V1 storage

If there is agreement I'll close this and edit the existing "remove Gov V1 storage" issue

**Comment by xlc** [comment]
Yeah they should be implemented together

**Comment by liamaharon** [comment]
Combined into https://github.com/paritytech/polkadot/issues/6749
