### ISSUE TITLE
Custom Voting and Authorship Rules for Availability

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#763]
We want the finalized chain to strongly imply availability in an honest case, and for the longest chain to be the "most available" chain.

We'll say that a relay chain block is availability-prepared by a validator when the validator has its availability piece for every parablock referenced in the block.

We'll say that a relay chain is availability-prepared by a validator when every block in that chain is availability-prepared by that validator, up to some relatively large `N` blocks before the chain head.

In the past, we've proposed 2 rules for validators to alter their chain-selection rules for GRANDPA voting and block construction.
  - Validators will vote only on chains that they have availability-prepared.
  - Validators will build only on chains whose k-prefix (The chain computed by omitting the last `k` blocks from the target chain) they have availability-prepared.

**Comment by rphmeier** [comment]
For implementation, we'll need a custom `SelectChain` implementation that is connected to the background task described in #475 . This `SelectChain`, when passed to the Sassafras authorship worker, and GRANDPA voting worker, should fulfill these rules.

**Comment by AlistairStewart** [comment]
Shouldn't sessions come into this? Rather than the last k blocks, it should really be all blocks in the same session, up to the off by one error for the start. The downside is if we are offline for part of a session, I suppose. Even if we can't do this, we don't need to check for pieces for already finalised blocks, in case we have just become a validator.

**Comment by burdges** [comment]
You meant to define availability-supplied somewhere? I guess you meant availability-prepared where you wrote availability-supplied. 

I presume the k-prefix rule is BABE not GRANDPA, but otherwise fine.

We've a zoo around secondary checks here, which grew more complex recently, but maybe that's not in this issue.

**Comment by rphmeier** [comment]
Yeah, the k-prefix is about BABE. 

> You meant to define availability-supplied somewhere? I guess you meant availability-prepared where you wrote availability-supplied.

@AlistairStewart 

> Shouldn't sessions come into this? Rather than the last k blocks, it should really be all blocks in the same session, up to the off by one error for the start.

Can you go into why sessions should come into this? What is the relation between sessions and availability?

**Comment by eskimor** [comment]
I think this is obsolete and can be closed? @rphmeier

**Comment by burdges** [comment]
Yes this predated two phases inclusion
