### ISSUE TITLE
api.rpc.payment.queryInfo

### ISSUE THREAD

**Issue by xihucuyu888** [paritytech/polkadot#889]
- v0.7.22
-  RPC-CORE: queryInfo(extrinsic: Bytes, at?: BlockHash): RuntimeDispatchInfo:: 2: Unable to query dispatch info.: Error("No such variant in enum Mu
(node:31674) UnhandledPromiseRejectionWarning: Error: queryInfo(extrinsic: Bytes, at?: BlockHash): RuntimeDispatchInfo:: 2: Unable to query dispatch info.: Error("No such variant in enum Mu

HsiaDmobwBdWEWxc8conidvJ4XHz3v94GMnX5AvsN1tpjc8

**Comment by bkchr** [comment]
CC @jacogr

**Comment by jacogr** [comment]
It will go away at block 1,375,086 on Kusama once the runtime upgrade takes effect.

The tx format has changed and the RPC node is currently ahead of the runtime and therefore decodes it incorrectly. The runtime expects `type Address = StaticLookup::Source` and the RPC use `type Address = AccountId`

**Comment by jacogr** [comment]
Closing, after the upgrade (despite some other issues), the RPC is working as expected again since the polkadot-node & runtime is in-sync with types. (The error was in-place since the bump to 0.7.22, which supported the 1055 runtime natively)

![image](https://user-images.githubusercontent.com/1424473/76229117-fe69a280-6221-11ea-9465-3cb378ab306a.png)
